# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "tufteTheme"
license = "MIT"
licenselink = "https://github.com/mseshachalam/tufte/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "mseshachalam"
  homepage = ""

# If porting an existing theme
[original]
  name = "spf13"
  homepage = "http://spf13.com/"
  repo = "https://github.com/spf13/hyde"
